font_family VictorMono Nerd Font
font_size 12

background #130c13
foreground #f5f5ff

selection_background #ff7fbf
selection_foreground #0b0b10

cursor #ff7fbf
cursor_shape block
cursor_blinking no

shell_integration no-cursor

window_padding_width 20

background_opacity 0.60

window_border_width 1
window_border_color #ff7fbf33

focus_follows_mouse yes
enable_audio_bell no

scrollback_lines 10000

active_tab_background #ff7fbf
active_tab_foreground #0b0b10

inactive_tab_background #181820
inactive_tab_foreground #b8b8cc

cursor_trail 100