-- Generated by nwg-displays on 2026-09-03 at 17:11:13. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "1920x1080@60.0",
    position = "1280x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "1280x1024@75.03",
    position = "0x56",
    scale = 1
})
